apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
data:
  PORT: "8005"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/343770067934/fiap-fase3-toggle-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  AWS_REGION: "us-east-1"
