apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flag-service

resources:
- ../../base

labels:
- pairs:
    environment: production

images:
- name: 343770067934.dkr.ecr.us-east-1.amazonaws.com/fiap/flag-service
  newTag: v1.0.0-edc574a
