name: Analytics Service - Deploy

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main2
  workflow_dispatch:


jobs:
  build-and-unit_test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"

  linter-static-analysis: 
    needs: build-and-unit_test
    name: Linter/Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"


  security-scan: 
    needs: linter-static-analysis
    name: Security Scan (SAST & SCA)
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"

  docker-build-and-push: 
    needs: security-scan
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"       
      

  update-helm-manifest: 
    needs: security-scan
    name: Update Helm Manifests
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"             
