name: Analytics Service - Deploy

on:
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main2
  workflow_dispatch:


jobs:
  build-and-unit_test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/analytics-service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: src/analytics-service/requirements-dev.txt

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest -v

  linter-static-analysis: 
    needs: build-and-unit_test
    name: Linter/Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"


  security-scan: 
    needs: linter-static-analysis
    name: Security Scan (SAST & SCA)
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"

  docker-build-and-push: 
    needs: security-scan
    name: Docker Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"       
      

  update-helm-manifest: 
    needs: docker-build-and-push
    name: Update Helm Manifests
    runs-on: ubuntu-latest

    steps:
      - name: teste
        run: echo "teste"             
